# 端口配置
server:
  port: 8888

# spring配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://soulbreath.cn:3306/jwt?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: soul
      password: Soul@143
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测,关闭空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true # 在空闲时检查
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache,并指定每个连接上PSCache的大小. oracle设为true,mysql设为false. 分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  # redis 配置
  redis:
    database: 0
    host: soulbreath.cn
    port: 6389
    password: Redis@143
    timeout: 6000ms
    jedis: # redis连接池
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1ms
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1

# mybatis 配置
mybatis:
  # 指定mapper文件路径
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 输出SQL执行语句
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 开启驼峰命名匹配
    map-underscore-to-camel-case: true
    # 在null时也调用 setter,适应于返回Map,3.2版本以上可用
    call-setters-on-nulls: true

# jwt 配置
jwt:
  # token过期时间
  expire: 2592000
  # 密钥
  secret: 5fe04e9fde17428ebf67053fc10ff9a7
  # header keyName(属性名)
  header: token

# 日志配置
logging:
  file: sb.log
  level:
    root: debug
